#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="${SCRIPT_DIR}/config"
mkdir -p "${CONFIG_DIR}"

# Usage:
#   ./gen_env.sh [node0_ip]
#
# Examples:
#   ./gen_env.sh                # node0_ip defaults to local_ip
#   ./gen_env.sh 10.10.10.1     # explicitly set master node IP

detect_local_ip() {
    local ip
    ip="$(ip -4 route get 223.5.5.5 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')"
    if [[ -n "${ip}" ]]; then
        echo "${ip}"
        return 0
    fi

    ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
    if [[ -n "${ip}" ]]; then
        echo "${ip}"
        return 0
    fi

    return 1
}

detect_nic_name() {
    local ip="$1"
    local nic

    nic="$(ip -4 route get 223.5.5.5 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}')"
    if [[ -n "${nic}" ]]; then
        echo "${nic}"
        return 0
    fi

    nic="$(ip -o -4 addr show 2>/dev/null | awk -v target_ip="${ip}" '$4 ~ ("^" target_ip "/") {print $2; exit}')"
    if [[ -n "${nic}" ]]; then
        echo "${nic}"
        return 0
    fi

    return 1
}

local_ip="$(detect_local_ip || true)"
if [[ -z "${local_ip}" ]]; then
    echo "[ERROR] Failed to detect local IPv4 address."
    exit 1
fi

nic_name="$(detect_nic_name "${local_ip}" || true)"
if [[ -z "${nic_name}" ]]; then
    echo "[ERROR] Failed to detect NIC name for local_ip=${local_ip}."
    exit 1
fi

node0_ip="${1:-${local_ip}}"
config_file="${CONFIG_DIR}/${local_ip}.env"

cat > "${config_file}" <<EOF
# Auto-generated by gen_env.sh on $(date '+%Y-%m-%d %H:%M:%S')
# For node IP: ${local_ip}

nic_name="${nic_name}"
local_ip="${local_ip}"
node0_ip="${node0_ip}"
EOF

echo "[OK] Generated config: ${config_file}"
echo "      nic_name=${nic_name}"
echo "      local_ip=${local_ip}"
echo "      node0_ip=${node0_ip}"
